---
- name: Install GNOME GSettings schemas + GNOME Shell (cross-distro)
  become: true
  vars:
    gnome_schema_packages:
      Archlinux:
        - glib2
        - gsettings-desktop-schemas
        - gnome-shell
      Debian:
        - libglib2.0-bin # provides gsettings
        - gsettings-desktop-schemas
        - gnome-shell
      Ubuntu:
        - libglib2.0-bin # provides gsettings
        - gsettings-desktop-schemas
        - gnome-shell
      Fedora:
        - glib2
        - gsettings-desktop-schemas
        - gnome-shell
      RedHat:
        - glib2
        - gsettings-desktop-schemas
        - gnome-shell
  ansible.builtin.package:
    name: >-
      {{
        gnome_schema_packages[ansible_facts['distribution']]
        | default(gnome_schema_packages[ansible_facts['os_family']])
        | default(gnome_schema_packages['RedHat'])
      }}
    state: present

- name: Include dependencies
  include_role:
    name: "{{ dependency_role }}"
  loop:
    - desk-gnome-caffeine
    - desk-gnome-extensions
    - desk-gnome-terminal
  loop_control:
    loop_var: dependency_role

- include_tasks: 02_extensions.yml

- include_tasks: utils/once/flag.yml
