---
- name: GNOME Activate Extensions
  ansible.builtin.shell: gsettings set org.gnome.shell disable-user-extensions false
  become: false

- name: "pkgmgr install"
  include_role:
    name: pkgmgr-install
  vars:
    package_name: cli-gnome-extension-manager

- name: Execute CLI GNOME Extension manager script
  ansible.builtin.shell: >-
    cli-gnome-extension-manager
    "{{ 'enable' if item.value.enabled | bool else 'disable' }}"
    "{{ item.value.config.uuid }}"
    "{{ item.value.config.url }}"
  loop: "{{ lookup('config', application_id, 'addons') | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
  become: false
