---
# nocheck: dynamic-flag
# nocheck: logout
logout:
  enabled: false
  shared: false
# nocheck: dynamic-flag
# nocheck: oidc
# nocheck: sso
sso:
  enabled: false
  shared: false
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
css:
  enabled: "{{ 'web-svc-css' in group_names }}"
  shared: "{{ 'web-svc-css' in group_names }}"
roulette-wheel:
  image: node
  version: latest
  repository: https://github.com/kevinveenbirkenbach/roulette-wheel.git
  ref: master
  min_storage: 1GB
  cpus: 0.5
  mem_reservation: 126m
  mem_limit: 265m
  pids_limit: 126
  ports:
    local:
      http: 8013
  run_after:
    - web-app-matomo
  lifecycle: alpha
# nocheck: email
# nocheck: dynamic-flag
email:
  enabled: false
  shared: false
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
