---
- services:
    dashboard: # nocheck: variants-services-match
      enabled: true
      shared: true
- services:
    dashboard: # nocheck: variants-services-match
      enabled: false
      shared: false
