---
- include_tasks: utils/once/flag.yml

- name: "load docker and db for {{ application_id }}"
  include_role:
    name: sys-stk-backend
  vars:
    compose_handlers_flush: false

- name: "create {{ FLOWISE_LITELLM_CONFIG_PATH_HOST }}"
  template:
    src: "litellm.config.yaml.j2"
    dest: "{{ FLOWISE_LITELLM_CONFIG_PATH_HOST }}"
  notify: compose up

- name: "flush handlers of compose"
  meta: flush_handlers

- name: "Include role sys-stk-front-proxy for '{{ application_id }}'"
  include_role:
    name: sys-stk-front-proxy
  vars:
    domain: "{{ lookup('domain',application_id) }}"
    http_port: "{{ lookup('config', application_id, 'services.flowise.ports.local.http') }}"
