---
# Matrix-deploy variant overrides for web-app-discourse.
# See docs/contributing/artefact/files/role/variants.md for the file format.

- services:
    asset:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    sso:
      enabled: true
      shared: true
    postgres:
      shared: true
    prometheus:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
- services:
    asset:
      enabled: false
      shared: false
    dashboard:
      enabled: false
      shared: false
    email:
      enabled: false
      shared: false
    logout:
      enabled: false
      shared: false
    matomo:
      enabled: false
      shared: false
    sso:
      enabled: false
      shared: false
    postgres:
      shared: false
    prometheus:
      enabled: false
      shared: false
    css:
      enabled: false
      shared: false
