---
- name: Include dependency 'sys-svc-webserver-https'
  include_role:
    name: sys-svc-webserver-https
  vars:
    compose_handlers_flush: true

- name: "Include domains redirects"
  include_tasks: redirect-domain.yml
  vars:
    domain: "{{ item.source }}"
    target: "{{ item.target }}"
  loop: "{{ redirect_domain_mappings }}"
