- include_tasks: utils/once/flag.yml

- name: "Remove stale oauth2-proxy config directory if it exists"
  ansible.builtin.file:
    path: "/opt/compose/{{ application_id }}/volumes/oauth2-proxy-keycloak.cfg"
    state: absent
  become: true

- name: "Load docker, db and proxy for {{ application_id }}"
  include_role:
    name: sys-stk-full
  vars:
    docker_compose_flush_handlers: false

- name: "Flush handlers"
  meta: flush_handlers

- name: "Run Pi-hole setup routines"
  include_tasks: 01_setup.yml
