---
galaxy_info:
  author: Prageeth Panicker
  description: Open-source SIEM and XDR platform for monitoring, log analysis, intrusion/vulnerability detection, and compliance
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  galaxy_tags:
    - wazuh
    - siem
    - xdr
    - security
    - monitoring
    - opensearch
    - self-hosted
    - docker
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
dependencies: []
