---
domains:
  canonical:
    - microblog.{{ DOMAIN_PRIMARY }}
  aliases: []
csp:
  flags:
    script-src-elem:
      unsafe-inline: true
  whitelist:
    frame-src:
      - "*"
    worker-src:
      - "blob:"
networks:
  local:
    subnet: 192.168.101.240/28
