---
enabled: "{{ lookup('config', 'web-app-wordpress', 'services.discourse.enabled') | bool }}"
required: false
mechanism: plugin
source: upstream
bridges:
  - discourse
update:
  monitored: true
  catalog: wordpress-org
  upstream_id: wp-discourse
config:
  discourse_settings:
    - name: discourse_connect
      key: url
      value: "{{ lookup('tls', 'web-app-discourse', 'url.base') }}"
    - name: discourse_connect
      key: api-key
      value: "{{ vault_discourse_api_key | default('') }}"
    - name: discourse_connect
      key: publish-username
      value: "system"
    - name: discourse_logs
      key: logs-enabled
      value: "{{ MODE_DEBUG }}"
