---
- include_tasks: utils/once/flag.yml

- name: "load docker, db and proxy for {{ application_id }}"
  include_role:
    name: sys-stk-full
  vars:
    webserver_client_max_body_size: "30m"
    compose_repository_url: "{{ OPENPROJECT_REPOSITORY }}"
    compose_repository_ref: "{{ OPENPROJECT_REF }}"
    compose_repository_pull: true
    compose_handlers_flush: false
    application_id: "web-app-openproject"

- name: "Create {{ OPENPROJECT_PLUGINS_FOLDER }}"
  file:
    path: "{{ OPENPROJECT_PLUGINS_FOLDER }}"
    state: directory
    mode: "0755"

- name: "Transferring Gemfile to {{ OPENPROJECT_PLUGINS_FOLDER }} as Gemfile.plugins"
  copy:
    src: Gemfile
    dest: "{{ [OPENPROJECT_PLUGINS_FOLDER,'Gemfile.plugins'] | path_join }}"
  notify:
    - compose up
    - compose build

- name: "create {{ OPENPROJECT_DUMMY_VOLUME }}"
  file:
    path: "{{ OPENPROJECT_DUMMY_VOLUME }}"
    state: directory
    mode: "0755"

- name: flush docker service
  meta: flush_handlers

- name: Deploy Settings
  include_tasks: 01_settings.yml

- name: Setup LDAP
  include_tasks: 02_ldap.yml
  when: OPENPROJECT_LDAP_ENABLED | bool

- name: Create OpenProject Administrator
  include_tasks: 03_admin.yml
