---
- name: Ensure nginx config directory exists
  ansible.builtin.file:
    path: "{{ lookup('nginx','files.configuration') | dirname }}"
    state: directory
    mode: "0755"

- name: Ensure base nginx.conf exists (bootstrap)
  ansible.builtin.copy:
    dest: "{{ lookup('nginx','files.configuration') }}"
    force: false
    mode: "0644"
    content: |
      events {}
      http { server { listen 8080; return 200; } }

- name: "For '{{ application_id }}': Load sys-svc-compose"
  include_role:
    name: sys-svc-compose
  vars:
    compose_repository_pull: false # Deactivated here to deactivate inhirement
    compose_handlers_flush: true
    application_id: svc-prx-openresty

- name: "Verify that '{{ role_name }}' works"
  include_tasks: 02_assert.yml
  when: MODE_ASSERT | bool

- include_tasks: utils/once/flag.yml
