"""Static-env passthrough: copy every declared key from default.env
with caller-env-wins (setdefault) semantics. Comments come from
``ctx.static_comments`` (parsed from default.env)."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from utils.env.builder import BuildContext, EnvBuilder

STATIC_KEYS = (
    "INFINITO_SRC_DIR",
    "INFINITO_BIND_IP",
    "INFINITO_BUILD",
    "INFINITO_SUBNET",
    "INFINITO_GATEWAY",
    "INFINITO_DISTRO",
    "INFINITO_DNS_DOMAIN",
    "INFINITO_DNS_HOSTS_FILE",
    "INFINITO_DNS_IP",
    "INFINITO_DOMAIN",
    "INFINITO_DOMAIN_RE",
    "INFINITO_CONTAINER",
    "INFINITO_CONTAINER_CA_ENABLED",
    "INFINITO_RUNNING_ON_ACT",
    "INFINITO_RUNNING_ON_GITHUB",
    "INFINITO_IS_WSL2",
    "INFINITO_PULL_POLICY",
    "INFINITO_MEM_LIMIT",
    "INFINITO_MEMSWAP_LIMIT",
    "INFINITO_CPUS",
    "INFINITO_WAIT_HEALTH_TIMEOUT_S",
    "INFINITO_DOCKER_VOLUME",
    "INFINITO_DOCKER_MOUNT",
    "INFINITO_IP4",
    "INFINITO_IP6",
    "INFINITO_PARENT_IMAGE",
    "INFINITO_PLAYWRIGHT_KEEP",
    "INFINITO_DEPLOY_TYPE",
    "INFINITO_TEST_PATTERN",
    "INFINITO_TEST_RUNNER",
    "INFINITO_LINT_RUNNER",
    "INFINITO_DISTROS",
    "INFINITO_APPS",
    "INFINITO_APP_DISCOVERY_RUNNER",
    "INFINITO_SERVICES_DISABLED",
    "INFINITO_BUILDKIT_ENABLED",
    "INFINITO_DEBUG",
    "INFINITO_WHITELIST",
    "INFINITO_LIMIT_HOST",
    "INFINITO_BUNDLES",
    "INFINITO_FULL_CYCLE",
    "INFINITO_VARIANT",
    "INFINITO_RUN_FLAGS",
    "INFINITO_WORKER_ENABLED",
    "INFINITO_INVENTORY_VARS_FILE",
    "INFINITO_CACHE_REGISTRY_HOST_PATH",
    "INFINITO_CACHE_REGISTRY_CA_HOST_PATH",
    "INFINITO_CACHE_PACKAGE_HOST_PATH",
    "INFINITO_CACHE_PACKAGE_PORT",
    "INFINITO_CACHE_PACKAGE_APT_LIST",
    "INFINITO_CACHE_PACKAGE_FRONTEND_CA_DIR",
    "INFINITO_CACHE_PACKAGE_FRONTEND_CA_FILE",
    "INFINITO_CACHE_PACKAGE_FRONTEND_CERTS_DIR",
    "INFINITO_CACHE_PACKAGE_FRONTEND_IP",
    "INFINITO_CACHE_PACKAGE_FRONTEND_INIT_IMAGE",
    "INFINITO_CACHE_PACKAGE_MAX_AGE_MIN",
    "INFINITO_CACHE_PACKAGE_NPMRC",
    "INFINITO_CACHE_PACKAGE_PIP_CONF",
    "INFINITO_CACHE_REGISTRY_PROXY_CONF",
    "INFINITO_IMAGE_TAG",
)


def apply(eb: EnvBuilder, ctx: BuildContext) -> None:
    for key in STATIC_KEYS:
        if key in ctx.static:
            eb.setdefault(
                key, ctx.static[key], comment=ctx.static_comments.get(key, "")
            )
