---
# General
application_id: "web-app-gitlab"
entity_name: "{{ application_id | get_entity_name }}"

# GitLab
GITLAB_URL: "{{ lookup('tls', application_id, 'url.base') }}"
GITLAB_HOSTNAME: "{{ lookup('domain',application_id) }}"

## Email
GITLAB_EMAIL: "{{ lookup('email', application_id) }}"
GITLAB_EMAIL_ENABLED: "{{ GITLAB_EMAIL.enabled | bool }}"

## OIDC
GITLAB_OIDC_ENABLED: "{{ lookup('config', application_id, 'services.oidc.enabled') }}"
GITLAB_OIDC_LABEL: "{{ OIDC.BUTTON_TEXT }}"
GITLAB_OIDC_UID_FIELD: "{{ OIDC.ATTRIBUTES.USERNAME }}"
GITLAB_OIDC_CLIENT_ID: "{{ OIDC.CLIENT.ID }}"
GITLAB_OIDC_CLIENT_SECRET: "{{ OIDC.CLIENT.SECRET }}"
GITLAB_OIDC_ISSUER: "{{ OIDC.CLIENT.ISSUER_URL }}"
GITLAB_OIDC_REDIRECT_URI: "{{ GITLAB_URL }}/users/auth/openid_connect/callback"

## Docker
GITLAB_INIT_ROOT_PASSWORD: "{{ lookup('users', 'administrator').password }}"
GITLAB_VERSION: "{{ lookup('config', application_id, 'services.gitlab.version') }}"
GITLAB_IMAGE: "{{ lookup('config', application_id, 'services.gitlab.image') }}"
GITLAB_CUSTOM_IMAGE: "{{ entity_name }}_custom:{{ GITLAB_VERSION }}"
GITLAB_CONTAINER: "{{ lookup('config', application_id, 'services.gitlab.name') }}"
GITLAB_CONF_VOLUME: "{{ lookup('config', application_id, 'volumes.config') }}"
GITLAB_LOGS_VOLUME: "{{ lookup('config', application_id, 'volumes.logs') }}"
GITLAB_DATA_VOLUME: "{{ lookup('config', application_id, 'volumes.data') }}"

## Configuration
GITLAB_OMNIBUS_BASE:
  - "external_url '{{ GITLAB_URL }}'"
  - "postgresql['enable']=false"
  - "gitlab_rails['gitlab_shell_ssh_port']={{ lookup('config', application_id, 'services.gitlab.ports.public.ssh') }}"
  - "gitlab_rails['db_adapter']='postgresql'"
  - "gitlab_rails['db_encoding']='utf8'"
  - "gitlab_rails['db_host']='{{ lookup('database', application_id, 'host') }}'"
  - "gitlab_rails['db_port']='{{ lookup('database', application_id, 'port') }}'"
  - "gitlab_rails['db_username']='{{ lookup('database', application_id, 'username') }}'"
  - "gitlab_rails['db_password']='{{ lookup('database', application_id, 'password') }}'"
  - "gitlab_rails['db_database']='{{ lookup('database', application_id, 'name') }}'"
  - "gitlab_rails['db_pool']={{ POSTGRES_ALLOWED_AVG_CONNECTIONS }}"
  - "nginx['listen_port']=80"
  - "nginx['listen_https']=false"
  - ""
  - "gitlab_rails['initial_root_password']={{ GITLAB_INIT_ROOT_PASSWORD | ruby_dq }}"
  - ""
  - "redis['enable']=false"
  - "gitlab_rails['redis_host']='redis'"
  - "gitlab_rails['redis_port']='6379'"

GITLAB_OMNIBUS_OIDC:
  - ""
  - "gitlab_rails['omniauth_enabled']=true"
  - "gitlab_rails['omniauth_allow_single_sign_on']=['openid_connect']"
  - "gitlab_rails['omniauth_block_auto_created_users']=false"
  - "gitlab_rails['omniauth_auto_link_user']=['openid_connect']"
  - "gitlab_rails['omniauth_providers']=[{ name: 'openid_connect', label: '{{ GITLAB_OIDC_LABEL | replace(\"'\",\"\\\\'\") }}', args: {"
  - "  name: 'openid_connect',"
  - "  scope: ['openid','profile','email'],"
  - "  response_type: 'code',"
  - "  issuer: '{{ GITLAB_OIDC_ISSUER | replace(\"'\",\"\\\\'\") }}',"
  - "  discovery: true,"
  - "  uid_field: '{{ GITLAB_OIDC_UID_FIELD | replace(\"'\",\"\\\\'\") }}',"
  - "  pkce: true,"
  - "  client_options: {"
  - "    identifier: '{{ GITLAB_OIDC_CLIENT_ID | replace(\"'\",\"\\\\'\") }}',"
  - "    secret: '{{ GITLAB_OIDC_CLIENT_SECRET | replace(\"'\",\"\\\\'\") }}',"
  - "    redirect_uri: '{{ GITLAB_OIDC_REDIRECT_URI | replace(\"'\",\"\\\\'\") }}'"
  - "  }"
  - "} }]"

GITLAB_OMNIBUS_SMTP:
  - ""
  - "gitlab_rails['smtp_enable']=true"
  - "gitlab_rails['smtp_address']={{ GITLAB_EMAIL.host | ruby_dq }}"
  - "gitlab_rails['smtp_port']={{ GITLAB_EMAIL.port }}"
  - "gitlab_rails['smtp_user_name']={{ GITLAB_EMAIL.username | ruby_dq }}"
  - "gitlab_rails['smtp_password']={{ GITLAB_EMAIL.password | ruby_dq }}"
  - "gitlab_rails['smtp_domain']={{ GITLAB_EMAIL.domain | ruby_dq }}"
  - "gitlab_rails['smtp_authentication']={{ (GITLAB_EMAIL.auth | bool) | ternary(\"'login'\", 'nil') }}"
  - "gitlab_rails['smtp_enable_starttls_auto']={{ GITLAB_EMAIL.start_tls | bool | string | lower }}"
  - "gitlab_rails['smtp_tls']={{ GITLAB_EMAIL.tls | bool | string | lower }}"
  - "gitlab_rails['gitlab_email_from']={{ GITLAB_EMAIL['from'] | ruby_dq }}"
  - "gitlab_rails['gitlab_email_reply_to']={{ GITLAB_EMAIL['from'] | ruby_dq }}"

GITLAB_OMNIBUS_ALL: "{{ GITLAB_OMNIBUS_BASE + (GITLAB_OMNIBUS_OIDC if GITLAB_OIDC_ENABLED else []) + (GITLAB_OMNIBUS_SMTP if GITLAB_EMAIL_ENABLED else []) }}"
