---
- name: "load docker, db and proxy for {{ application_id }}"
  include_role:
    name: sys-stk-full
  vars:
    compose_handlers_flush: false
    webserver_extra_configuration: >-
      {% if not LISTMONK_PUBLIC_API_ENABLED | bool %}
      {{ lookup('file', '{{ playbook_dir }}/roles/web-app-listmonk/files/deactivate-public-api.conf') }}
      {% else %}
      ""
      {% endif %}

- name: add config.toml
  template:
    src: "config.toml.j2"
    dest: "{{ LISTMONK_CONFIG_HOST }}"
  notify: compose up

- meta: flush_handlers

- name: Include database setup routine for Listmonk
  include_tasks: "01_database.yml"

- name: Build OIDC settings JSON
  set_fact:
    oidc_settings_json: >-
      {{ {
         "enabled":       True,
         "client_id":     OIDC.CLIENT.ID,
         "provider_url":  OIDC.CLIENT.ISSUER_URL,
         "client_secret": OIDC.CLIENT.SECRET
      } | to_json }}

- name: Update administrator email and password login in Listmonk (as superuser)
  shell: |
    {{ LISTMONK_EXEC_DATABASE }} -v ON_ERROR_STOP=1 << 'EOSQL'
    UPDATE users
    SET email = '{{ lookup('users', 'administrator').email }}',
        password_login = {{ 'false' if lookup('config',application_id, 'services.sso.enabled') else 'true' }}
    WHERE username = 'administrator';
    EOSQL
  args:
    executable: /bin/bash

- name: Apply all Listmonk settings
  shell: |
    {{ LISTMONK_EXEC_DATABASE }} -v ON_ERROR_STOP=1 << 'EOSQL'
    UPDATE settings
    SET value = '{{ item.value }}'::jsonb
    WHERE key = '{{ item.key }}';
    EOSQL
  args:
    executable: /bin/bash
  loop: "{{ LISTMONK_SETTINGS }}"
  loop_control:
    label: "{{ item.key }}"
  when: (item.when | default(true)) | bool
  no_log: "{{ MASK_CREDENTIALS_IN_LOGS | bool }}"
  async: "{{ ASYNC_TIME if ASYNC_ENABLED | bool else omit }}"
  poll: "{{ ASYNC_POLL if ASYNC_ENABLED | bool else omit }}"
