---
- services:
    matrix:
      flavor: ansible
    coturn:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    postgres:
      shared: true
    sso:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
    seaweedfs:
      enabled: true
      shared: true

- services:
    matrix:
      flavor: ansible
    coturn:
      enabled: false
      shared: false
    css:
      enabled: false
      shared: false
    dashboard:
      enabled: false
      shared: false
    email:
      enabled: false
      shared: false
    ldap:
      enabled: false
      shared: false
    logout:
      enabled: false
      shared: false
    matomo:
      enabled: false
      shared: false
    postgres:
      shared: false
    sso:
      enabled: false
      shared: false
    prometheus:
      enabled: false
      shared: false
    seaweedfs:
      enabled: false
      shared: false

- services:
    matrix:
      flavor: compose
    seaweedfs:
      enabled: true
      shared: true
    coturn:
      enabled: true
      shared: true
    css:
      enabled: true
      shared: true
    dashboard:
      enabled: true
      shared: true
    email:
      enabled: true
      shared: true
    ldap:
      enabled: true
      shared: true
    logout:
      enabled: true
      shared: true
    matomo:
      enabled: true
      shared: true
    postgres:
      shared: true
    sso:
      enabled: true
      shared: true
    prometheus:
      enabled: true
      shared: true
