# General
application_id:           "web-app-pihole"
entity_name:              "{{ application_id | get_entity_name }}"
domain:                   "{{ lookup('domain', application_id) }}"

# Pi-hole
PIHOLE_VERSION:           "{{ lookup('config', application_id, 'services.pihole.version') }}"
PIHOLE_IMAGE:             "{{ lookup('config', application_id, 'services.pihole.image') }}"
PIHOLE_CONTAINER:         "{{ entity_name }}"
PIHOLE_UPSTREAM_DNS:      "1.1.1.1;1.0.0.1"
PIHOLE_TIMEZONE:          "{{ HOST_TIMEZONE }}"

# OAuth2 enabled
PIHOLE_OAUTH2_ENABLED:    "{{ lookup('config', application_id, 'services.oauth2.enabled') | bool }}"
PIHOLE_PASSWORD:          "{{ '' if PIHOLE_OAUTH2_ENABLED else lookup('password', application_id, 'admin') }}"
