credentials:
  secret_key:
    description: Penpot secret key used to sign application data
    algorithm: alphanumeric
    validation:
      min_length: 64
    default: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=64') }}"