csp:
networks:
  local:
    subnet: 192.168.105.48/28
  flags:
    script-src:
      unsafe-eval: true
    script-src-elem:
      unsafe-inline: true
      unsafe-eval: true
    script-src-attr:
      unsafe-inline: true
      unsafe-eval: true
    style-src-attr:
      unsafe-inline: true
domains:
  canonical:
    - penpot.design.{{ DOMAIN_PRIMARY }}