---
logout:
  enabled: "{{ 'web-svc-logout' in group_names }}"
  shared: "{{ 'web-svc-logout' in group_names }}"
# nocheck: dynamic-flag
# nocheck: oidc
# nocheck: sso
sso:
  enabled: false
  shared: false
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
# nocheck: dynamic-flag
# nocheck: email
email:
  enabled: false
  shared: false
postgres:
  enabled: true # nocheck: dynamic-flag
  shared: "{{ 'svc-db-postgres' in group_names }}"
confluence:
  image: atlassian/confluence
  version: latest
  name: confluence
  min_storage: 20GB
  cpus: "3.0"
  mem_reservation: 6g
  mem_limit: 8g
  pids_limit: 2048
  truststore_enabled: false
  ports:
    local:
      http: 8005
  run_after:
    - web-app-matomo
  lifecycle: unsupported
css:
  enabled: "{{ 'web-svc-css' in group_names }}"
  shared: "{{ 'web-svc-css' in group_names }}"
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
