---
# General
application_id: "web-app-taiga"
entity_name: "{{ application_id | get_entity_name }}"

# Taiga

## General
TAIGA_EMAIL_BACKEND: "{{ 'smtp' if lookup('email', application_id).smtp else 'console' }}" # # use an SMTP server or display the emails in the console (either "smtp" or "console")

## User
TAIGA_SUPERUSER_NAME: "{{ lookup('users', 'administrator').username }}"
TAIGA_SUPERUSER_PASSWORD: "{{ lookup('users', 'administrator').password }}"
TAIGA_SUPERUSER_EMAIL: "{{ lookup('users', 'administrator').email }}"

## Authentication
TAIGA_OIDC_ENABLED: "{{ lookup('config', application_id, 'services.sso.enabled') }}"
TAIGA_LDAP_ENABLED: "{{ lookup('config', application_id, 'services.ldap.enabled', false) }}"
TAIGA_PLUGINS_ENABLED: "{{ TAIGA_OIDC_ENABLED | bool or TAIGA_LDAP_ENABLED | bool }}"
TAIGA_CONFIG_APPEND_MARKER: "INFINITO_TAIGA_AUTH_CONFIG"
TAIGA_OIDC_PLUGIN_REPOSITORY: "{{ lookup('config', application_id, 'services.sso.oidc.repository') }}"
TAIGA_OIDC_PLUGIN_REF: "{{ lookup('config', application_id, 'services.sso.oidc.ref') }}"
TAIGA_OIDC_BACKEND_PIP_SPEC: "{{ 'git+' ~ TAIGA_OIDC_PLUGIN_REPOSITORY ~ '@' ~ TAIGA_OIDC_PLUGIN_REF ~ '#egg=taiga-contrib-oidc-auth&subdirectory=back' }}"
TAIGA_OIDC_FRONTEND_BUILD_COMMAND: "./node_modules/.bin/gulp build"
TAIGA_LDAP_PIP_SPEC: "taiga-contrib-ldap-auth-ext==0.5.0"
TAIGA_PLUGIN_PIP_INSTALL_ARGS: >-
  {{
    (
      (
        ['mozilla-django-oidc', "'" ~ TAIGA_OIDC_BACKEND_PIP_SPEC ~ "'"]
        if TAIGA_OIDC_ENABLED | bool
        else []
      )
      +
      (
        [TAIGA_LDAP_PIP_SPEC]
        if TAIGA_LDAP_ENABLED | bool
        else []
      )
    ) | join(' ')
  }}

## Docker
TAIGA_REPOSITORY: "{{ lookup('config', application_id, 'services.taiga.repository') }}"
TAIGA_REF: "{{ lookup('config', application_id, 'services.taiga.ref') }}"
TAIGA_VERSION: "{{ lookup('config', application_id, 'services.taiga.version') }}"
TAIGA_CONFIG_DIRECTORY: "{{ lookup('container', application_id, 'directories.config') }}"
TAIGA_INSTANCE_DIRECTORY: "{{ lookup('container', application_id, 'directories.instance') }}"
TAIGA_COMPOSE_INIT_PATH: "{{ [TAIGA_INSTANCE_DIRECTORY, 'compose-inits.yml'] | path_join }}"
TAIGA_CONFIG_APPEND_PATH: "{{ [TAIGA_CONFIG_DIRECTORY, 'taiga-config.append.py'] | path_join }}"
TAIGA_URLS_PATH: "{{ [TAIGA_CONFIG_DIRECTORY, 'taiga-urls.py'] | path_join }}"
TAIGA_FRONTEND_CONF_PATH: "{{ [TAIGA_CONFIG_DIRECTORY, 'conf.json'] | path_join }}"
TAIGA_DOCKER_IMAGE_BACKEND: "taigaio/taiga-back"
TAIGA_DOCKER_IMAGE_BACKEND_AUTH: "{{ entity_name }}-back-auth:{{ TAIGA_VERSION }}"
TAIGA_DOCKER_IMAGE_FRONTEND: "taigaio/taiga-front"
TAIGA_DOCKER_IMAGE_FRONTEND_OIDC: "{{ entity_name }}-front-oidc:{{ TAIGA_VERSION }}"
TAIGA_DOCKER_IMAGE_EVENTS: "{{ lookup('config', application_id, 'services.events.image') }}"
TAIGA_DOCKER_VERSION_EVENTS: "{{ lookup('config', application_id, 'services.events.version') }}"
TAIGA_DOCKER_IMAGE_PROTECTED: "{{ lookup('config', application_id, 'services.protected.image') }}"
TAIGA_DOCKER_VERSION_PROTECTED: "{{ lookup('config', application_id, 'services.protected.version') }}"
TAIGA_DOCKER_IMAGE_GATEWAY: "{{ lookup('config', application_id, 'services.gateway.image') }}"
TAIGA_DOCKER_VERSION_GATEWAY: "{{ lookup('config', application_id, 'services.gateway.version') }}"
TAIGA_DOCKER_IMAGE_ASYNC_RABBITMQ: "{{ lookup('config', application_id, 'services.async-rabbitmq.image') }}"
TAIGA_DOCKER_VERSION_ASYNC_RABBITMQ: "{{ lookup('config', application_id, 'services.async-rabbitmq.version') }}"
TAIGA_DOCKER_IMAGE_EVENTS_RABBITMQ: "{{ lookup('config', application_id, 'services.events-rabbitmq.image') }}"
TAIGA_DOCKER_VERSION_EVENTS_RABBITMQ: "{{ lookup('config', application_id, 'services.events-rabbitmq.version') }}"

### Backend
TAIGA_SERVICE: "{{ entity_name }}"
TAIGA_HOSTNAME: "taiga-back"
TAIGA_CONTAINER: "{{ entity_name }}"
TAIGA_VOLUME_MEDIA: "/taiga-back/media"
TAIGA_VOLUME_STATIC: "/taiga-back/static"

## Services
TAIGA_MANAGER_SERVICE: "manager"
TAIGA_ASYNC_SERVICE: "async"
TAIGA_ASYNC_RABBITMQ_SERVICE: "async-rabbitmq"
TAIGA_EVENTS_RABBITMQ_SERVICE: "events-rabbitmq"
TAIGA_FRONT_SERVICE: "front"
TAIGA_EVENTS_SERVICE: "events"
