---
- name: Include Cloudflare redirect rule to enforce www → apex
  include_tasks: _02_cloudflare_redirect_rule.yml
  vars:
    domain: "{{ item.target }}"
    www_fqdn: "{{ item.source }}"
    apex_url: "{{ lookup('tls', application_id, 'protocols.web') }}://{{ item.target }}"
  loop: "{{ REDIRECT_WWW_DOMAINS }}"
