---
- name: 📂 Include dependency 'sys-ctl-mtn-cert-renew'
  include_role:
    name: sys-ctl-mtn-cert-renew
  when:
    - run_once_sys_ctl_mtn_cert_renew is not defined
    - lookup('tls', domain | default(application_id), 'mode') == 'letsencrypt'

- name: 📁 Create HTTP->HTTPS handler per domain
  stack_host_template:
    src: "http.conf.j2"
    dest: "{{ lookup('nginx', 'files.domain', domain, protocol='http') }}"
  notify: restart-openresty
  when: HTTPS_REDIRECT_ENABLED | bool
