# nocheck: shared
# nocheck: dynamic-flag
# nocheck: playwright-service-flag
oauth2:
  enabled: true
  shared: true
  allowed_groups:
  - '{{ lookup(''rbac_group_path'', application_id=''web-app-pihole'', role=''administrator'') }}'
  origin:
    host: pihole
    port: 80
# nocheck: dynamic-flag
# nocheck: playwright-service-flag
logout:
  enabled: true
  shared: true
# nocheck: dynamic-flag
# nocheck: playwright-service-flag
dashboard:
  enabled: true
  shared: true
# nocheck: dynamic-flag
# nocheck: playwright-service-flag
matomo:
  enabled: true
  shared: true
# nocheck: email
# nocheck: dynamic-flag
# nocheck: playwright-service-flag
email:
  enabled: false
  shared: true
# nocheck: dynamic-flag
# nocheck: playwright-service-flag
redis:
  enabled: true
  shared: true
# nocheck: dynamic-flag
# nocheck: playwright-service-flag
javascript:
  enabled: true
  shared: true
# nocheck: dynamic-flag
# nocheck: playwright-service-flag
prometheus:
  enabled: true
  shared: true
pihole:
  image: pihole/pihole
  version: latest
  upstream_dns: "{{ NETWORK_PUBLIC_DNS_RESOLVERS }}"
  cpus: "0.5"
  mem_reservation: "128m"
  mem_limit: "256m"
  min_storage: "1GB"
  pids_limit: 512
  ports:
    local:
      http: 8041
      oauth2: 16505
  run_after:
  - web-app-keycloak
  lifecycle: alpha
