---
sso:
  enabled: "{{ 'web-app-keycloak' in group_names }}"
  shared: "{{ 'web-app-keycloak' in group_names }}"
  flavor: oidc
logout:
  enabled: "{{ 'web-svc-logout' in group_names }}"
  shared: "{{ 'web-svc-logout' in group_names }}"
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
email:
  enabled: "{{ 'web-app-mailu' in group_names }}"
  shared: "{{ 'web-app-mailu' in group_names }}"
postgres:
  enabled: true # nocheck: dynamic-flag
  shared: "{{ 'svc-db-postgres' in group_names }}"
  extensions:
    - postgis
    - pg_trgm
    - unaccent
mobilizon:
  image: docker.io/kaihuri/mobilizon
  name: mobilizon
  version: 5.2.3
  min_storage: 5GB
  titel: Mobilizon on {{ DOMAIN_PRIMARY | upper }}
  ports:
    local:
      http: 8043
  run_after:
    - web-app-matomo
    - web-app-keycloak
    - web-app-mailu
  lifecycle: beta
  cpus: "0.2"
  mem_reservation: 128m
  mem_limit: 256m
  pids_limit: 256
css:
  enabled: "{{ 'web-svc-css' in group_names }}"
  shared: "{{ 'web-svc-css' in group_names }}"
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
