---
sso:
  enabled: "{{ 'web-app-keycloak' in group_names }}"
  shared: "{{ 'web-app-keycloak' in group_names }}"
  flavor: oauth2
  oauth2:
    origin:
      host: suitecrm
      port: "80"
logout:
  enabled: "{{ 'web-svc-logout' in group_names }}"
  shared: "{{ 'web-svc-logout' in group_names }}"
ldap:
  enabled: "{{ 'svc-db-openldap' in group_names }}"
  shared: "{{ 'svc-db-openldap' in group_names }}"
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
email:
  enabled: "{{ 'web-app-mailu' in group_names }}"
  shared: "{{ 'web-app-mailu' in group_names }}"
mariadb:
  enabled: true # nocheck: dynamic-flag
  shared: "{{ 'svc-db-mariadb' in group_names }}"
suitecrm:
  image: php
  # TODO: Make SuiteCRM compatible with PHP 8.5; update currently not possible. Reason: intentional legacy pin.
  # nocheck: docker-version
  version: 8.2-apache
  app_version: 8.9.1
  name: suitecrm
  min_storage: 10GB
  cpus: 1.5
  mem_reservation: 1.2g
  mem_limit: 2g
  pids_limit: 768
  email:
    from_name: Customer Relationship Management (SuiteCRM, {{ DOMAIN_PRIMARY }})
  maintenance_mode: false
  ports:
    local:
      sso: 16490
      http: 8062
  run_after:
    - web-app-keycloak
    - web-app-mailu
    - web-app-matomo
  lifecycle: beta
css:
  enabled: "{{ 'web-svc-css' in group_names }}"
  shared: "{{ 'web-svc-css' in group_names }}"
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
