---
funkwhale:
  image: funkwhale/front
  version: 2.0.2
  min_storage: 20GB
  ports:
    local:
      sso: 16502
      http: 8012
  run_after:
    - web-app-matomo
    - web-app-keycloak
    - web-app-mailu
  lifecycle: beta
  cpus: "1.0"
  mem_reservation: 1g
  mem_limit: 2g
  pids_limit: 1024
api:
  image: funkwhale/api
  version: 2.0.2
  min_storage: 5GB
  cpus: "0.5"
  mem_reservation: 256m
  mem_limit: 1g
  pids_limit: 512
typesense:
  image: typesense/typesense
  version: "30.2"
  min_storage: 1GB
  cpus: "0.2"
  mem_reservation: 128m
  mem_limit: 256m
  pids_limit: 256
logout:
  enabled: "{{ 'web-svc-logout' in group_names }}"
  shared: "{{ 'web-svc-logout' in group_names }}"
ldap:
  enabled: "{{ 'svc-db-openldap' in group_names }}"
  shared: "{{ 'svc-db-openldap' in group_names }}"
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
email:
  enabled: "{{ 'web-app-mailu' in group_names }}"
  shared: "{{ 'web-app-mailu' in group_names }}"
# nocheck: shared
# nocheck: dynamic-flag
redis:
  backup:
    disabled: true
  enabled: true
postgres:
  enabled: true # nocheck: dynamic-flag
  shared: "{{ 'svc-db-postgres' in group_names }}"
sso:
  enabled: "{{ 'web-app-keycloak' in group_names }}"
  shared: "{{ 'web-app-keycloak' in group_names }}"
  flavor: oauth2
  oauth2:
    origin:
      host: front
      port: "80"
    acl:
      blacklist:
        - /login
css:
  enabled: "{{ 'web-svc-css' in group_names }}"
  shared: "{{ 'web-svc-css' in group_names }}"
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
