---
# nocheck: dynamic-flag
# nocheck: logout
logout:
  enabled: false
  shared: false
# nocheck: dynamic-flag
# nocheck: sso
sso:
  enabled: false
  shared: false
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
postgres:
  enabled: true # nocheck: dynamic-flag
  shared: "{{ 'svc-db-postgres' in group_names }}"
chess:
  image: ghcr.io/kevinveenbirkenbach/fedi-chess
  version: v1.0.1
  name: web-app-chess
  min_storage: 5GB
  backup:
    no_stop_required: true
  cpus: 0.5
  mem_reservation: 256m
  mem_limit: 512m
  pids_limit: 256
  ports:
    local:
      http: 8050
  lifecycle: beta
css:
  enabled: "{{ 'web-svc-css' in group_names }}"
  shared: "{{ 'web-svc-css' in group_names }}"
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
