---
mini-qr:
  image: ghcr.io/lyqht/mini-qr
  version: latest
  ports:
    local:
      http: 8059
  lifecycle: beta
  min_storage: 1GB
  cpus: "0.2"
  mem_reservation: 128m
  mem_limit: 256m
  pids_limit: 256
# nocheck: dynamic-flag
# nocheck: logout
logout:
  enabled: false
  shared: false
# nocheck: dynamic-flag
# nocheck: sso
sso:
  enabled: false
  shared: false
dashboard:
  enabled: "{{ 'web-app-dashboard' in group_names }}"
  shared: "{{ 'web-app-dashboard' in group_names }}"
matomo:
  enabled: "{{ 'web-app-matomo' in group_names }}"
  shared: "{{ 'web-app-matomo' in group_names }}"
# nocheck: dynamic-flag
redis:
  backup:
    disabled: true
  enabled: false
css:
  enabled: "{{ 'web-svc-css' in group_names }}"
  shared: "{{ 'web-svc-css' in group_names }}"
prometheus:
  enabled: "{{ 'web-app-prometheus' in group_names }}"
  shared: "{{ 'web-app-prometheus' in group_names }}"
