---
enabled: "{{ lookup('config', 'web-app-nextcloud', 'services.bigbluebutton.enabled') | bool }}"
required: true
mechanism: plugin
source: upstream
bridges:
  - bigbluebutton
update:
  monitored: true
  catalog: nextcloud-appstore
  upstream_id: bbb
config:
  plugin_configuration:
    - appid: "bbb"
      configkey: "api.secret"
      configvalue: "{{ lookup('config','web-app-bigbluebutton', 'credentials.shared_secret', '') }}"
    - appid: "bbb"
      configkey: "api.url"
      configvalue: "{{ lookup('tls', 'web-app-bigbluebutton', 'url.base') }}{{ lookup('config', 'web-app-bigbluebutton', 'services.bigbluebutton.api_suffix','') }}"
