---
enabled: "{{ lookup('sso_oidc_plugin') == 'sociallogin' }}"
required: true
mechanism: plugin
source: upstream
bridges:
  - sso
update:
  monitored: true
  catalog: nextcloud-appstore
  upstream_id: sociallogin
config:
  mandatory: true
  incompatible_plugins:
    - user_oidc
    - oidc_login
  plugin_configuration:
    - appid: "sociallogin"
      configkey: "allow_login_connect"
      configvalue: 1
    - appid: "sociallogin"
      configkey: "auto_create_groups"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "button_text_wo_prefix"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "create_disabled_users"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "custom_providers"
      configvalue:
        custom_oidc:
          - name: "{{ lookup('domain','web-app-keycloak') }}"
            title: "keycloak"
            style: "keycloak"
            authorizeUrl: "{{ OIDC.CLIENT.AUTHORIZE_URL }}"
            tokenUrl: "{{ OIDC.CLIENT.TOKEN_URL }}"
            displayNameClaim: ""
            userInfoUrl: "{{ OIDC.CLIENT.USER_INFO_URL }}"
            logoutUrl: "{{ OIDC.CLIENT.LOGOUT_URL }}"
            clientId: "{{ OIDC.CLIENT.ID }}"
            clientSecret: "{{ OIDC.CLIENT.SECRET }}"
            scope: "openid"
            groupsClaim: ""
            defaultGroup: ""
    - appid: "sociallogin"
      configkey: "disable_notify_admins"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "disable_registration"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "enabled"
      configvalue: "yes"
    - appid: "sociallogin"
      configkey: "hide_default_login"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "no_prune_user_groups"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "oauth_providers"
      configvalue: "null"
    - appid: "sociallogin"
      configkey: "prevent_create_email_exists"
      configvalue: 1
    - appid: "sociallogin"
      configkey: "restrict_users_wo_assigned_groups"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "restrict_users_wo_mapped_groups"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "types"
      configvalue: ""
    - appid: "sociallogin"
      configkey: "update_profile_on_login"
      configvalue: 1
