---
enabled: false
required: false
mechanism: bridge
source: upstream
update:
  monitored: true
  catalog: mautrix
  upstream_id: mautrix-facebook
config:
  bridge_name: "facebook"
  database_username: "mautrix_facebook_bridge"
  database_name: "mautrix_facebook_bridge"
  database_password: "{{ lookup('config', 'web-app-matrix', 'credentials.mautrix_facebook_bridge_database_password') }}"
