---
enabled: false
required: false
mechanism: bridge
source: upstream
update:
  monitored: true
  catalog: mautrix
  upstream_id: mautrix-signal
config:
  bridge_name: "signal"
  database_username: "mautrix_signal_bridge"
  database_name: "mautrix_signal_bridge"
  database_password: "{{ lookup('config', 'web-app-matrix', 'credentials.mautrix_signal_bridge_database_password') }}"
