---
enabled: false
required: false
mechanism: bridge
source: upstream
update:
  monitored: true
  catalog: mautrix
  upstream_id: mautrix-whatsapp
config:
  bridge_name: "whatsapp"
  database_username: "mautrix_whatsapp_bridge"
  database_name: "mautrix_whatsapp_bridge"
  database_password: "{{ lookup('config', 'web-app-matrix', 'credentials.mautrix_whatsapp_bridge_database_password') }}"
