---
enabled: false
required: false
mechanism: bridge
source: upstream
update:
  monitored: true
  catalog: mautrix
  upstream_id: mautrix-telegram
config:
  bridge_name: "telegram"
  database_username: "mautrix_telegram_bridge"
  database_name: "mautrix_telegram_bridge"
  database_password: "{{ lookup('config', 'web-app-matrix', 'credentials.mautrix_telegram_bridge_database_password') }}"
