---
# General
application_id: "web-app-openwebui"

# Open WebUI
# https://openwebui.com/
OPENWEBUI_URL: "{{ lookup('tls', application_id, 'url.base') }}"
OPENWEBUI_VERSION: "{{ lookup('config', application_id, 'services.openwebui.version') }}"
OPENWEBUI_IMAGE: "{{ lookup('config', application_id, 'services.openwebui.image') }}"
OPENWEBUI_CONTAINER: "{{ lookup('config', application_id, 'services.openwebui.name') }}"
OPENWEBUI_OFFLINE_MODE: "{{ lookup('config', application_id, 'services.openwebui.offline_mode') }}"
OPENWEBUI_HF_HUB_OFFLINE: "{{ lookup('config', application_id, 'services.openwebui.hf_hub_offline') }}"
OPENWEBUI_VOLUME: "{{ lookup('config', application_id, 'volumes.openwebui') }}"
OPENWEBUI_PORT_PUBLIC: "{{ lookup('config', application_id, 'services.openwebui.ports.local.http') }}"
OPENWEBUI_LDAP_ENABLED: "{{ lookup('config', application_id, 'services.ldap.enabled') }}"

## OIDC
OPENWEBUI_OIDC_ENABLED: "{{ lookup('config', application_id, 'services.sso.enabled') }}"
OPENWEBUI_OIDC_REDIRECT_URL: "{{ [OPENWEBUI_URL,'/oauth/oidc/callback'] | url_join }}"
OPENWEBUI_OIDC_ADMIN_GROUP: "{{ lookup('rbac_group_path', application_id=application_id, role='administrator') }}"
