---
galaxy_info:
  author: Kevin Veen-Birkenbach
  description: Jitsi Meet is an open-source video conferencing platform with end-to-end encrypted rooms and federated authentication.
  license: Infinito.Nexus Community License (Non-Commercial)
  company: |
    Kevin Veen-Birkenbach
    https://www.veen.world
  galaxy_tags:
    - jitsi
    - meet
    - video
    - conferencing
    - webrtc
    - docker
  issue_tracker_url: https://s.infinito.nexus/issues
  min_ansible_version: "2.9"
  platforms:
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
