---
runner_name: "{{ inventory_hostname }}"
runner_distribution: ""
runner_labels: "self-hosted,linux,{{ runner_distribution }}"
runner_count: "{{ [ansible_processor_vcpus | int // RUNNER_CPUS | int, 1] | max }}"
INFINITO_IMAGE_TAG: "{{ lookup('env', 'INFINITO_IMAGE_TAG') | default('latest', true) }}"  # nocheck
INFINITO_GHCR_MIRROR_PREFIX: "{{ lookup('env', 'INFINITO_GHCR_MIRROR_PREFIX') | default('', true) }}"  # nocheck
