---
# General
application_id: "web-app-gitea"

# Docker
container_port: "{{ lookup('config', application_id, 'services.gitea.ports.internal.http') }}"

# Gitea
GITEA_LDAP_AUTH_ARGS:
  - '--name "LDAP ({{ DOMAIN_PRIMARY }})"'
  - '--host "{{ LDAP.SERVER.DOMAIN }}"'
  - "--port {{ LDAP.SERVER.PORT }}"
  - '--security-protocol "{{ LDAP.SERVER.SECURITY | trim or "unencrypted" }}"'
  - '--bind-dn "{{ LDAP.DN.ADMINISTRATOR.DATA }}"'
  - '--bind-password "{{ LDAP.BIND_CREDENTIAL }}"'
  - '--user-search-base "{{ LDAP.DN.OU.USERS }}"'
  - '--user-filter "(&(objectClass=inetOrgPerson)(uid=%s))"'
  - '--admin-filter "(memberOf=cn={{ application_id }}-administrator,{{ LDAP.DN.OU.ROLES }})"'
  - '--username-attribute "{{ LDAP.USER.ATTRIBUTES.ID }}"'
  - '--firstname-attribute "{{ LDAP.USER.ATTRIBUTES.FIRSTNAME }}"'
  - '--surname-attribute "{{ LDAP.USER.ATTRIBUTES.SURNAME }}"'
  - '--email-attribute "{{ LDAP.USER.ATTRIBUTES.MAIL }}"'
  - '--public-ssh-key-attribute "{{ LDAP.USER.ATTRIBUTES.SSH_PUBLIC_KEY }}"'
  - "--synchronize-users"
GITEA_VERSION: "{{ lookup('config', application_id, 'services.gitea.version') }}"
GITEA_IMAGE: "{{ lookup('config', application_id, 'services.gitea.image') }}"
GITEA_CONTAINER: "{{ lookup('config', application_id, 'services.gitea.name') }}"
GITEA_VOLUME: "{{ lookup('config', application_id, 'volumes.data') }}"
GITEA_USER: "git"
GITEA_CONFIG: "/data/gitea/conf/app.ini"

## Redis
GITEA_REDIS_ENABLED: "{{ lookup('config', application_id, 'services.redis.enabled') }}"
GITEA_REDIS_ADDRESS: "redis:6379"

GITEA_OIDC_ENABLED: "{{ lookup('config', application_id, 'services.sso.shared') | bool }}"
GITEA_LDAP_ENABLED: "{{ lookup('config', application_id, 'services.ldap.enabled') }}"
GITEA_IAM_ENABLED: "{{ (GITEA_OIDC_ENABLED | bool) or ( GITEA_LDAP_ENABLED | bool ) }}"
