---
mariadb:
  enabled: true
  shared: true
  version: "12.3"
  image: mariadb
  name: mariadb
  min_storage: 10GB
  backup:
    database_routine: true
  cpus: "2.0"
  mem_reservation: 2g
  mem_limit: 4g
  pids_limit: 1024
  ports:
    local:
      mariadb: 3306
  lifecycle: beta
